databases:
  - name: emgmt
    plan: free
    databaseName: emgmt
    user: emgmt

services:
  - type: web
    name: emgmt
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: emgmt
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
